### ISSUE TITLE
Adding AzureDataExplorer to Azure services

### ISSUE THREAD

**Issue by ag-ramachandran** [mathworks-ref-arch/matlab-azure-services#1]
Hello!

First of all thanks a lot for such fantastic integration capabilities with Azure Auth & support for all the auth options.
As part of onboarding [Azure Data Explorer](https://azure.microsoft.com/en-in/products/data-explorer/#overview), we'd like to take next steps on the best way forward.
Is there a way to contribute & extend support to this new DB from Matlab. We could have a conversation on this (or) If there is a specific contributing guide & we can follow it would be great!

**Comment by brownemi** [comment]
Hi Ramachandran A G,

Thanks, glad you like the package, if you could please email mwlabs@mathworks.com we'd be happy to arrange a call to discuss the matter.

**Comment by brownemi** [comment]
v1.0.1 adds Azure Data Explorer support, closing issue, thanks for your support in doing so.
